export const KEEP_BEFORE_ROUTE_CHANGE = 'KEEP_BEFORE_ROUTE_CHANGE';
export const KEEP_ROUTE_CHANGE = 'KEEP_ROUTE_CHANGE';
export const KEEP_COMPONENT_DESTROY = 'KEEP_COMPONENT_DESTROY';
export const KEEP_SUBSCRIBE_COMPLETE = 'KEEP_SUBSCRIBE_COMPLETE';

export const RE_LAUNCH = 'reLaunch';
export const DESTROY_ALL = 'ALL';

