#!/usr/bin/env sh
commit_regex='^Merge.+|(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .{1,50}'

if ! grep -iqE "$commit_regex" "$1"; then
    echo
    echo "  \033[31m 错误：提交日志生成需要正确的提交消息格式。 \033[0m"
    echo
    echo "  使用\033[32m npm run commit\033[0m 以交互方式生成提交消息。"
    echo "  - 有关更多详细信息，请参阅 cz.config.js"
    echo
    exit 1
fi
